#!/bin/bash
if [ -f ./sync-dailies.config ]; then
  . sync-dailies.config
else
  echo "Config not found. Please enter current cycle with this:"
  echo "sync-dailies newconfig <codename> <releasever>"
  exit 1
fi
if [ -d ./${RELEASE}-beta ]; then
  cd ${RELEASE}-beta
else
  mkdir ${RELEASE}-beta
  cd ${RELEASE}-beta
fi
if [ "${MIRROR}" = "" ]; then
  MIRROR=http://cdimage.ubuntu.com
fi
zsync ${MIRROR}/edubuntu/releases/${CODENAME}/beta/edubuntu-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Edubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/edubuntu/releases/${CODENAME}/beta/edubuntu-${RELEASE}-beta-preinstalled-desktop-arm64+raspi.img.xz.zsync -i  ./Edubuntu/${CODENAME}-preinstalled-desktop-arm64+raspi.img.xz
zsync ${MIRROR}/kubuntu/releases/${CODENAME}/beta/kubuntu-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Kubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/lubuntu/releases/${CODENAME}/beta/lubuntu-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Lubuntu/${CODENAME}-desktop-amd64.iso
zsync http://releases.ubuntu.com/${CODENAME}/ubuntu-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Ubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntu/releases/${CODENAME}/beta/ubuntu-${RELEASE}-beta-preinstalled-desktop-arm64+raspi.img.xz.zsync -i ../Ubuntu/${CODENAME}-preinstalled-desktop-arm64+raspi.img.xz
zsync ${MIRROR}/ubuntu-budgie/releases/${CODENAME}/beta/ubuntu-budgie-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Ubuntu\ Budgie/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntucinnamon/releases/${CODENAME}/beta/ubuntucinnamon-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Ubuntu\ Cinnamon/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntukylin/releases/${CODENAME}/beta/ubuntukylin-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Ubuntu\ Kylin/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntu-mate/releases/${CODENAME}/beta/ubuntu-mate-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Ubuntu\ MATE/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntustudio/releases/${CODENAME}/beta/ubuntustudio-${RELEASE}-beta-dvd-amd64.iso.zsync -i ../Ubuntu\ Studio/${CODENAME}-dvd-amd64.iso
zsync ${MIRROR}/ubuntu-unity/releases/${CODENAME}/beta/ubuntu-unity-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Ubuntu\ Unity/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/xubuntu/releases/${CODENAME}/beta/xubuntu-${RELEASE}-beta-desktop-amd64.iso.zsync -i ../Xubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/xubuntu/releases/${CODENAME}/beta/xubuntu-${RELEASE}-beta-minimal-amd64.iso.zsync -i ../Xubuntu/${CODENAME}-minimal-amd64.iso
