#!/bin/bash
if [ -f ./sync-dailies.config ]; then
  . sync-dailies.config
else
  echo "Config not found. Please enter current cycle with this:"
  echo "sync-dailies newconfig <codename> <releasever>"
  exit 1
fi
if [ -d ./${RELEASE}-release ]; then
  cd ${RELEASE}-release
else
  mkdir ${RELEASE}-release
  cd ${RELEASE}-release
fi
if [ "${MIRROR}" = "" ]; then
  MIRROR=http://cdimage.ubuntu.com
fi
zsync ${MIRROR}/edubuntu/releases/${CODENAME}/release/edubuntu-${RELEASE}-desktop-amd64.iso.zsync -i ../edubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/edubuntu/releases/${CODENAME}/release/edubuntu-${RELEASE}-preinstalled-desktop-arm64+raspi.img.xz.zsync -i  ../edubuntu/${CODENAME}-preinstalled-desktop-arm64+raspi.img.xz
zsync ${MIRROR}/kubuntu/releases/${CODENAME}/release/kubuntu-${RELEASE}-desktop-amd64.iso.zsync -i ../kubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/lubuntu/releases/${CODENAME}/release/lubuntu-${RELEASE}-desktop-amd64.iso.zsync -i ../lubuntu/${CODENAME}-desktop-amd64.iso
zsync http://releases.ubuntu.com/${CODENAME}/ubuntu-${RELEASE}-desktop-amd64.iso.zsync -i ../ubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntu/releases/${CODENAME}/release/ubuntu-${RELEASE}-preinstalled-desktop-arm64+raspi.img.xz.zsync -i ../ubuntu/${CODENAME}-preinstalled-desktop-arm64+raspi.img.xz
zsync ${MIRROR}/ubuntu-budgie/releases/${CODENAME}/release/ubuntu-budgie-${RELEASE}-desktop-amd64.iso.zsync -i ../ubuntu-budgie/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntucinnamon/releases/${CODENAME}/release/ubuntucinnamon-${RELEASE}-desktop-amd64.iso.zsync -i ../ubuntucinnamon/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntukylin/releases/${CODENAME}/release/ubuntukylin-${RELEASE}-desktop-amd64.iso.zsync -i ../ubuntukylin/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntu-mate/releases/${CODENAME}/release/ubuntu-mate-${RELEASE}-desktop-amd64.iso.zsync -i ../ubuntu-mate/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/ubuntustudio/releases/${CODENAME}/release/ubuntustudio-${RELEASE}-dvd-amd64.iso.zsync -i ../ubuntustudio/${CODENAME}-dvd-amd64.iso
zsync ${MIRROR}/ubuntu-unity/releases/${CODENAME}/release/ubuntu-unity-${RELEASE}-desktop-amd64.iso.zsync -i ../ubuntu-unity/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/xubuntu/releases/${CODENAME}/release/xubuntu-${RELEASE}-desktop-amd64.iso.zsync -i ../xubuntu/${CODENAME}-desktop-amd64.iso
zsync ${MIRROR}/xubuntu/releases/${CODENAME}/release/xubuntu-${RELEASE}-minimal-amd64.iso.zsync -i ../xubuntu/${CODENAME}-minimal-amd64.iso
